name: Delete Old Deployments
on:
  workflow_dispatch:

jobs:
  clear-deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Deployments
        uses: strumwolf/delete-deployment-environment-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: Production
          onlyRemoveDeployments: true
